name: Build and Push Docker Image

# on:
#   push:
#     branches:
#       - main  # Trigger on pushes to the main branch

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select the browser'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Display selected browser
        run: echo "Selected browser: ${{ github.event.inputs.browser }}"
     
      - name: Configure npm for private registry
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.EP_NPM_TOKEN }}" > .npmrc
              
      - name: Install dependencies
        run: yarn install
        env:
          NPM_TOKEN: ${{ secrets.EP_NPM_TOKEN }}
          
      - name: Build Docker image
        run: |
          docker build \
            --build-arg NPM_TOKEN=${{ secrets.EP_NPM_TOKEN }} \
            -t ${{ secrets.DOCKER_USERNAME }}/chrome:126.0.6478.61-1 .
        
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Docker image to DockerHub
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/chrome:126.0.6478.61-1 ${{ secrets.DOCKER_USERNAME }}/chrome:126.0.6478.61-1
          docker push ${{ secrets.DOCKER_USERNAME }}/chrome:126.0.6478.61-1
      
      # - name: Install dependencies
      #   run: npm install

      # # Log in to Docker Hub
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # # Build the Docker image
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v3
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   with:
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/chrome:latest
      #     platforms: linux/amd64
